// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdgjvjvcgtcnwjkvbcgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZ2p2anZjZ3Rjbndqa3ZiY2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Mjk1NjMsImV4cCI6MjA2MjEwNTU2M30.qRBhdngXvoEwNXXbzJhlUr617XmYhbV1t4sd53h6O8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);